# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 420bddb44d6708e258de8afc8f2d874431da770e29c3bf4313f4f815e0ddb8f775d96091ef5c3ce3af9ec57c5a857e59c2ff5cb35c229c0ec4a704832e56fd39

test:
  secret_key_base: 53533ad1850536cdde6c8d535fc87e9a0e16ec52220f796c14a8750c26188a2cbf2d42ae3782394df8b9e76a8670d564f44a217e21db1952dd221ae6f56e7f51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
